### ISSUE TITLE
Library not found for -lAmbly

### ISSUE THREAD

**Issue by theronic** [mfikes/shrimp#8]
1. I ran `pod install --repo-update` from the iOS directory (also upgraded to Cocoapods 1.6.1)
2. I ran ./repl.sh and it shows "Searching for Devices ..."
3. Open iOS project in XCode version 10.2 beta 4 (10P107d), and when I try to build for iPhone simulator, it shows error "ld: library not found for -lAmbly"

![image](https://user-images.githubusercontent.com/1011676/54840173-0b217d80-4cd5-11e9-953c-ce24609807ae.png)

I tried cleaning out library search paths, set to `$(inherited)`, but can't get it to build. 

![image](https://user-images.githubusercontent.com/1011676/54840179-11aff500-4cd5-11e9-81b1-3cb54233eba7.png)

I haven't used XCode for a while, so I'm sure this is something wrong with my environment, but I have no idea what.

**Comment by mfikes** [comment]
@theronic Did you perchance open `Shrimp.xcodeproj` instead of `Shrimp.xcworkspace`? (CocoaPods sets things up so that deps are available in the `*.xcworkspace`.)

**Comment by theronic** [comment]
Yup :) Thanks! That sounds like some hard-earned arcana.
